language: go
go_import_path: github.com/twitchtv/retool

go:
- 1.7.5
- 1.8
- tip

script:
- go install ./...
- go test -v -race $(go list ./... | grep -v /vendor/)
- retool sync
- retool do gometalinter --install
- retool do gometalinter ./... --vendor --disable gocyclo --disable gas --disable goconst
