language: go
go_import_path: github.com/twitchtv/retool

os:
  - linux
  - osx

go:
- 1.9.7
- 1.10.4
- 1.11
- tip

script:
- go install ./...
- go test -v -race $(go list ./... | grep -v /vendor/)
- go vet $(go list ./... | grep -v /vendor/)
- go tool vet -shadow *.go

- retool build
- retool do errcheck .
- retool do deadcode .
- retool do varcheck .
- retool do aligncheck .
- retool do structcheck .
- retool do ineffassign .
